[package]
name = "ag-dsl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "README.md"
description = "Lexer, parser, analisis semantico y codegen del Anti-DSL"
keywords.workspace = true
categories.workspace = true
publish = false

[lints]
workspace = true
