[package]
name = "ag-auth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "README.md"
description = "Autenticacion y autorizacion: WebAuthn, JWT Ed25519, OAuth2, RBAC"
keywords.workspace = true
categories.workspace = true
publish = false

[lints]
workspace = true

[features]
default = []
persistent = ["dep:ag-data"]

[dependencies]
ag-data = { workspace = true, optional = true }
blake3 = { workspace = true }
base64ct = { workspace = true }
getrandom = { workspace = true }
jsonwebtoken = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
webauthn-rs = { workspace = true }
oauth2 = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true }
ed25519-dalek = { workspace = true }
rand_core = { workspace = true }
