[package]
name = "ag-auth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "README.md"
description = "Autenticacion y autorizacion: WebAuthn, JWT Ed25519, OAuth2, RBAC"
keywords.workspace = true
categories.workspace = true
publish = false

[lints]
workspace = true
