//! HMAC-SHA256 signed URLs for ag-storage.
//!
//! A signed URL is valid only if:
//! 1. The HMAC signature matches (integrity + authenticity).
//! 2. The `expires_at` timestamp has not passed.
//!
//! Token format: `{base64url(hmac)}_{expires_at_secs}`
//! The signature covers: `key_bytes || expires_at_be_bytes`.

use base64ct::{Base64Url, Encoding};
use hmac::{Hmac, Mac};
use sha2::Sha256;

type HmacSha256 = Hmac<Sha256>;

/// Error returned when verifying a signed URL.
#[derive(Debug, PartialEq)]
#[non_exhaustive]
pub enum SignedUrlError {
    /// The signature does not match (possible tampering).
    InvalidSignature,
    /// The URL has expired.
    Expired,
    /// Invalid token format.
    InvalidFormat,
    /// Empty secret key (signed URLs not configured).
    NoSecret,
}

impl std::fmt::Display for SignedUrlError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SignedUrlError::InvalidSignature => write!(f, "invalid signature"),
            SignedUrlError::Expired => write!(f, "expired URL"),
            SignedUrlError::InvalidFormat => write!(f, "invalid token format"),
            SignedUrlError::NoSecret => write!(f, "STORAGE_SIGN_SECRET not configured"),
        }
    }
}

impl std::error::Error for SignedUrlError {}

/// Generates the signature part of the token for `key` with expiry `expires_at`.
///
/// Returns `"<base64url_hmac>_<expires_at>"`.
pub fn sign_url(secret: &str, key: &str, expires_at: u64) -> Result<String, SignedUrlError> {
    if secret.is_empty() {
        return Err(SignedUrlError::NoSecret);
    }
    let mac = compute_hmac(secret.as_bytes(), key, expires_at);
    let sig_b64 = Base64Url::encode_string(&mac);
    Ok(format!("{sig_b64}_{expires_at}"))
}

/// Verifies a token generated by `sign_url`.
///
/// Returns `Ok(())` if the signature is valid and the token has not expired.
pub fn verify_signed_url(secret: &str, key: &str, token: &str) -> Result<(), SignedUrlError> {
    if secret.is_empty() {
        return Err(SignedUrlError::NoSecret);
    }

    let (sig_b64, expires_str) = token
        .rsplit_once('_')
        .ok_or(SignedUrlError::InvalidFormat)?;

    let expires_at: u64 = expires_str
        .parse()
        .map_err(|_| SignedUrlError::InvalidFormat)?;

    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    if now > expires_at {
        return Err(SignedUrlError::Expired);
    }

    let expected_mac = compute_hmac(secret.as_bytes(), key, expires_at);
    let provided_sig =
        Base64Url::decode_vec(sig_b64).map_err(|_| SignedUrlError::InvalidSignature)?;

    if expected_mac.len() != provided_sig.len() {
        return Err(SignedUrlError::InvalidSignature);
    }
    let mismatch = expected_mac
        .iter()
        .zip(provided_sig.iter())
        .fold(0u8, |acc, (a, b)| acc | (a ^ b));
    if mismatch != 0 {
        return Err(SignedUrlError::InvalidSignature);
    }

    Ok(())
}

fn compute_hmac(secret: &[u8], key: &str, expires_at: u64) -> Vec<u8> {
    let mut mac = HmacSha256::new_from_slice(secret).expect("HMAC accepts keys of any length");
    mac.update(key.as_bytes());
    mac.update(&expires_at.to_be_bytes());
    mac.finalize().into_bytes().to_vec()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn future_ts() -> u64 {
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs()
            + 3600
    }

    fn past_ts() -> u64 {
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs()
            .saturating_sub(3600)
    }

    #[test]
    fn sign_and_verify_roundtrip() {
        let secret = "super-secret-key";
        let key = "avatars/user-42.jpg";
        let expires = future_ts();
        let token = sign_url(secret, key, expires).expect("sign must succeed");
        verify_signed_url(secret, key, &token).expect("verify must succeed");
    }

    #[test]
    fn expired_token_rejected() {
        let secret = "secret";
        let key = "docs/report.pdf";
        let token = sign_url(secret, key, past_ts()).unwrap();
        let result = verify_signed_url(secret, key, &token);
        assert_eq!(result, Err(SignedUrlError::Expired));
    }

    #[test]
    fn wrong_key_rejected() {
        let secret = "secret";
        let expires = future_ts();
        let token = sign_url(secret, "original-key", expires).unwrap();
        let result = verify_signed_url(secret, "other-key", &token);
        assert_eq!(result, Err(SignedUrlError::InvalidSignature));
    }

    #[test]
    fn wrong_secret_rejected() {
        let expires = future_ts();
        let key = "file.txt";
        let token = sign_url("correct-secret", key, expires).unwrap();
        let result = verify_signed_url("wrong-secret", key, &token);
        assert_eq!(result, Err(SignedUrlError::InvalidSignature));
    }

    #[test]
    fn tampered_token_rejected() {
        let secret = "secret";
        let expires = future_ts();
        let token = sign_url(secret, "file.txt", expires).unwrap();
        // Replace the last character of the signature (before '_') to simulate
        // token tampering without using unsafe.
        let underscore_pos = token.find('_').unwrap();
        let tampered = if underscore_pos > 0 {
            let mut chars: Vec<char> = token.chars().collect();
            let idx = underscore_pos - 1;
            chars[idx] = if chars[idx] == 'A' { 'B' } else { 'A' };
            chars.into_iter().collect::<String>()
        } else {
            format!("X{}", &token[1..])
        };
        let result = verify_signed_url(secret, "file.txt", &tampered);
        assert!(result.is_err());
    }

    #[test]
    fn empty_secret_returns_no_secret_error() {
        let result = sign_url("", "key.txt", future_ts());
        assert_eq!(result, Err(SignedUrlError::NoSecret));
    }

    #[test]
    fn invalid_token_format_rejected() {
        let result = verify_signed_url("secret", "key.txt", "not-a-token");
        assert_eq!(result, Err(SignedUrlError::InvalidFormat));
    }

    #[test]
    fn different_keys_produce_different_tokens() {
        let secret = "s";
        let expires = future_ts();
        let t1 = sign_url(secret, "file1.txt", expires).unwrap();
        let t2 = sign_url(secret, "file2.txt", expires).unwrap();
        assert_ne!(t1, t2);
    }
}

#[cfg(test)]
mod prop_tests {
    //! Property-based tests (audit Stage 5) for the signed-URL invariants:
    //! a fresh token always verifies; a token never verifies under a different
    //! key or secret; any signature tamper is rejected; expired tokens fail.
    use super::*;
    use proptest::prelude::*;

    // Far-future expiry so the time check never triggers in roundtrip tests.
    const FUTURE: u64 = u64::MAX;

    proptest! {
        #[test]
        fn fresh_token_always_verifies(secret in "[!-~]{1,64}", key in "[!-~]{0,128}") {
            let token = sign_url(&secret, &key, FUTURE).unwrap();
            prop_assert_eq!(verify_signed_url(&secret, &key, &token), Ok(()));
        }

        #[test]
        fn different_key_is_rejected(
            secret in "[!-~]{1,64}", a in "[!-~]{0,64}", b in "[!-~]{0,64}",
        ) {
            prop_assume!(a != b);
            let token = sign_url(&secret, &a, FUTURE).unwrap();
            prop_assert!(verify_signed_url(&secret, &b, &token).is_err());
        }

        #[test]
        fn different_secret_is_rejected(
            s1 in "[!-~]{1,64}", s2 in "[!-~]{1,64}", key in "[!-~]{0,64}",
        ) {
            prop_assume!(s1 != s2);
            let token = sign_url(&s1, &key, FUTURE).unwrap();
            prop_assert!(verify_signed_url(&s2, &key, &token).is_err());
        }

        #[test]
        fn tampered_signature_is_rejected(secret in "[!-~]{1,64}", key in "[!-~]{0,64}") {
            let token = sign_url(&secret, &key, FUTURE).unwrap();
            // Flip the first byte (always part of the base64url signature).
            let mut bytes = token.into_bytes();
            bytes[0] ^= 0x01;
            let tampered = String::from_utf8_lossy(&bytes).into_owned();
            prop_assert!(verify_signed_url(&secret, &key, &tampered).is_err());
        }

        #[test]
        fn expired_token_is_rejected(secret in "[!-~]{1,64}", key in "[!-~]{0,64}") {
            // expires_at = 0 (1970) is always in the past.
            let token = sign_url(&secret, &key, 0).unwrap();
            prop_assert_eq!(
                verify_signed_url(&secret, &key, &token),
                Err(SignedUrlError::Expired)
            );
        }
    }
}
