[package]
name = "ag-realtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "README.md"
description = "Tiempo real: WebSocket, SSE y pub/sub con bus de eventos"
keywords.workspace = true
categories.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
axum = { workspace = true }
futures-util = { workspace = true }
rmp-serde = { workspace = true }
tokio-stream = { workspace = true }
async-nats = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }

[features]
nats-external = ["dep:async-nats", "dep:thiserror"]
event-persistence = []

[dev-dependencies]
tokio-test = { workspace = true }
tokio = { workspace = true, features = ["test-util", "fs"] }
rcgen = { workspace = true }
tempfile = { workspace = true }
