//! Handler stubs generated by Anti-Gravital ag-dsl v0.2.
//! Implement the body of each function to complete the API.

#![allow(unused_variables, clippy::unused_async)]

use super::types::*;
use super::AppState;
use ag_core::core::Claims;
use axum::extract::Path;
use axum::extract::State;
use axum::Json;

/// PATCH /users/{id} - UpdateUser
pub async fn update_user(
    State(state): State<AppState>,
    Path(id): Path<String>,
    Claims(claims): Claims<serde_json::Value>,
    Json(body): Json<UpdateUser>,
) -> Result<Json<UserResponse>, axum::http::StatusCode> {
    todo!()
}
