//! Models generated by Anti-Gravital ag-dsl v0.1.
//! DO NOT edit manually. Regenerate with `ag generate`.

#![allow(dead_code, missing_docs)]

use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Full model (includes automatically generated fields).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct User {
    pub id: Uuid,
    pub email: String,
}

/// POST request body to create a new record.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateUserRequest {
    pub email: String,
}

/// PUT/PATCH request body to update a record.
/// Fields are optional: only the ones provided are updated.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct UpdateUserRequest {
    pub email: Option<String>,
}
