//! Router generated by Anti-Gravital ag-dsl v0.2.

use super::{handlers, AppState};
use axum::routing;

/// Creates the Axum router with all routes defined in the schema.
pub fn api_router() -> axum::Router<AppState> {
    axum::Router::new().route("/users/:id", routing::patch(handlers::update_user))
}
