//! API types generated by Anti-Gravital ag-dsl v0.2.
//! DO NOT edit manually. Regenerate with `ag generate`.

#![allow(dead_code, missing_docs)]

use serde::{Deserialize, Serialize};

/// Request body for `UpdateUser`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpdateUser {
    pub email: String,
}

impl UpdateUser {
    /// Validates every constraint declared in the DSL schema.
    /// Returns all validation errors; an empty list means the value is valid.
    pub fn validate(&self) -> Vec<String> {
        let mut errors: Vec<String> = Vec::new();
        if !(self.email.contains('@')
            && self
                .email
                .rfind('@')
                .map(|i| self.email[i + 1..].contains('.'))
                .unwrap_or(false))
        {
            errors.push("email: invalid email format".to_owned());
        }
        errors
    }
}

/// Response body for `UserResponse`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserResponse {
    pub id: uuid::Uuid,
    pub email: String,
}
