//! Rust generator for DSL v0.1-v0.2.
//!
//! Produces Rust structs with serde from the schema models (v0.1),
//! and API types + handler stubs + router from endpoints (v0.2).

use crate::ast::{
    extract_path_params, to_snake_case, Annotation, AuthMode, EndpointDef, FieldDef, FieldType,
    HttpMethod, ModelDef, RequestDef, ResponseDef, Schema,
};

/// Generates the root module that makes all Rust artifacts a coherent unit.
pub fn generate_module(schema: &Schema) -> String {
    let mut out = String::from(
        "//! Rust API module generated by Anti-Gravital.\n\
         //! DO NOT edit manually. Regenerate with `ag generate`.\n\n",
    );
    if !schema.endpoints.is_empty() {
        out.push_str("pub mod handlers;\n");
    }
    out.push_str("pub mod models;\n");
    if !schema.endpoints.is_empty() {
        out.push_str("pub mod router;\n");
    }
    if !schema.requests.is_empty() || !schema.responses.is_empty() || !schema.errors.is_empty() {
        out.push_str("pub mod types;\n");
    }
    out.push_str("\n/// Application state used by generated handlers and routers.\n");
    out.push_str("pub type AppState = ag_core::core::AppState;\n");
    out
}

/// Generates the contents of the `src/models.rs` file for the given schema.
pub fn generate_models(schema: &Schema) -> String {
    let mut out = String::new();

    out.push_str("//! Models generated by Anti-Gravital ag-dsl v0.1.\n");
    out.push_str("//! DO NOT edit manually. Regenerate with `ag generate`.\n\n");
    out.push_str("#![allow(dead_code, missing_docs)]\n\n");

    // Base imports
    let needs_uuid = schema
        .models
        .iter()
        .any(|m| m.fields.iter().any(|f| f.ty.value == FieldType::Uuid));
    let needs_chrono = schema
        .models
        .iter()
        .any(|m| m.fields.iter().any(|f| f.ty.value == FieldType::Timestamp));
    let needs_decimal = schema
        .models
        .iter()
        .any(|m| m.fields.iter().any(|f| f.ty.value == FieldType::Decimal));

    out.push_str("use serde::{Deserialize, Serialize};\n");
    if needs_uuid {
        out.push_str("use uuid::Uuid;\n");
    }
    if needs_chrono {
        out.push_str("use chrono::{DateTime, Utc};\n");
    }
    if needs_decimal {
        out.push_str("use rust_decimal::Decimal;\n");
    }
    out.push('\n');

    for model in &schema.models {
        out.push_str(&generate_model_struct(model));
        out.push('\n');
        out.push_str(&generate_create_request(model));
        out.push('\n');
        out.push_str(&generate_update_request(model));
        out.push('\n');
    }

    out
}

/// Full model struct (all fields).
fn generate_model_struct(model: &ModelDef) -> String {
    let name = &model.name.value;
    let mut out = String::new();

    out.push_str("/// Full model (includes automatically generated fields).\n");
    out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    out.push_str(&format!("pub struct {name} {{\n"));

    for field in &model.fields {
        let fname = &field.name.value;
        if field.virtual_field {
            let rust_ty = match &field.ty.value {
                FieldType::ModelRef(m) => format!("Option<{m}>"),
                FieldType::ModelRefList(m) => format!("Vec<{m}>"),
                _ => continue,
            };
            out.push_str(&format!("    pub {fname}: {rust_ty},\n"));
        } else if field.ty.value == FieldType::Uuid && fname == "id" {
            out.push_str("    pub id: Uuid,\n");
        } else {
            let rust_ty = rust_field_type(field);
            out.push_str(&format!("    pub {fname}: {rust_ty},\n"));
        }
    }

    out.push_str("}\n");
    out
}

/// Creation request: excludes @auto and @auto_update fields.
fn generate_create_request(model: &ModelDef) -> String {
    let name = &model.name.value;
    let create_fields: Vec<_> = model
        .fields
        .iter()
        .filter(|f| !is_auto_generated(f) && !f.virtual_field)
        .collect();

    if create_fields.is_empty() {
        // All fields are auto-generated; a create request makes no sense.
        return format!(
            "/// All fields in '{name}' are generated automatically.\n\
             /// No create request is required.\n\n"
        );
    }

    let mut out = String::new();
    out.push_str("/// POST request body to create a new record.\n");
    out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    out.push_str(&format!("pub struct Create{name}Request {{\n"));

    for field in create_fields {
        let rust_ty = rust_field_type(field);
        let fname = &field.name.value;
        out.push_str(&format!("    pub {fname}: {rust_ty},\n"));
    }

    out.push_str("}\n");
    out
}

/// Update request: all non-auto fields are Option<T>.
fn generate_update_request(model: &ModelDef) -> String {
    let name = &model.name.value;
    let update_fields: Vec<_> = model
        .fields
        .iter()
        .filter(|f| !is_auto_generated(f) && !is_primary(f) && !f.virtual_field)
        .collect();

    if update_fields.is_empty() {
        return format!("/// '{name}' has no updatable fields.\n\n");
    }

    let mut out = String::new();
    out.push_str("/// PUT/PATCH request body to update a record.\n");
    out.push_str("/// Fields are optional: only the ones provided are updated.\n");
    out.push_str("#[derive(Debug, Clone, Serialize, Deserialize, Default)]\n");
    out.push_str(&format!("pub struct Update{name}Request {{\n"));

    for field in update_fields {
        let base_ty = field.ty.value.rust_type(false);
        let fname = &field.name.value;
        out.push_str(&format!("    pub {fname}: Option<{base_ty}>,\n"));
    }

    out.push_str("}\n");
    out
}

/// Returns the Rust type of the field, taking optionality into account.
fn rust_field_type(field: &FieldDef) -> String {
    // @auto or @auto_update fields are always present in the DB,
    // but in response structs they are included as required.
    field.ty.value.rust_type(field.optional)
}

/// True if the field has @auto or @auto_update.
fn is_auto_generated(field: &FieldDef) -> bool {
    field
        .annotations
        .iter()
        .any(|a| matches!(a.value, Annotation::Auto | Annotation::AutoUpdate))
}

/// True if the field has @primary.
fn is_primary(field: &FieldDef) -> bool {
    field
        .annotations
        .iter()
        .any(|a| a.value == Annotation::Primary)
}

// ---- DSL v0.2 generators --------------------------------------------

/// Generates `src/types.rs`: request, response, and error definitions.
///
/// Returns an empty string when the schema has no API types.
pub fn generate_types(schema: &Schema) -> String {
    if schema.requests.is_empty() && schema.responses.is_empty() && schema.errors.is_empty() {
        return String::new();
    }
    let mut out = String::new();
    out.push_str("//! API types generated by Anti-Gravital ag-dsl v0.2.\n");
    out.push_str("//! DO NOT edit manually. Regenerate with `ag generate`.\n\n");
    out.push_str("#![allow(dead_code, missing_docs)]\n\n");
    out.push_str("use serde::{Deserialize, Serialize};\n");

    out.push('\n');

    for req in &schema.requests {
        out.push_str(&generate_request_struct(req));
        out.push('\n');
    }
    for resp in &schema.responses {
        out.push_str(&generate_response_struct(resp));
        out.push('\n');
    }
    for err in &schema.errors {
        out.push_str(&format!(
            "/// HTTP error {}: {}\n",
            err.status.value, err.message.value
        ));
        out.push_str(&format!(
            "pub const {}_STATUS: u16 = {};\n",
            to_snake_case(&err.name.value).to_uppercase(),
            err.status.value
        ));
        out.push_str(&format!(
            "pub const {}_MESSAGE: &str = \"{}\";\n\n",
            to_snake_case(&err.name.value).to_uppercase(),
            err.message.value
        ));
    }
    out
}

fn generate_request_struct(req: &RequestDef) -> String {
    let name = &req.name.value;
    let mut out = String::new();
    out.push_str(&format!("/// Request body for `{name}`.\n"));
    out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    out.push_str(&format!("pub struct {name} {{\n"));
    for field in &req.fields {
        let rust_ty = field.ty.value.rust_type(field.optional);
        let fname = &field.name.value;
        out.push_str(&format!("    pub {fname}: {rust_ty},\n"));
    }
    out.push_str("}\n");
    out.push_str(&generate_validate_impl(name, &req.fields));
    out
}

fn generate_response_struct(resp: &ResponseDef) -> String {
    let name = &resp.name.value;
    let mut out = String::new();
    out.push_str(&format!("/// Response body for `{name}`.\n"));
    out.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    out.push_str(&format!("pub struct {name} {{\n"));
    for field in &resp.fields {
        let rust_ty = field.ty.value.rust_type(field.optional);
        let fname = &field.name.value;
        out.push_str(&format!("    pub {fname}: {rust_ty},\n"));
    }
    out.push_str("}\n");
    out
}

/// Generates `src/handlers.rs`: Axum handler stubs.
pub fn generate_handlers(schema: &Schema) -> String {
    if schema.endpoints.is_empty() {
        return String::new();
    }
    let mut out = String::new();
    out.push_str("//! Handler stubs generated by Anti-Gravital ag-dsl v0.2.\n");
    out.push_str("//! Implement the body of each function to complete the API.\n\n");
    out.push_str("#![allow(unused_variables, clippy::unused_async)]\n\n");
    let has_path_params = schema
        .endpoints
        .iter()
        .any(|ep| !extract_path_params(&ep.path.value).is_empty());
    let has_json = schema
        .endpoints
        .iter()
        .any(|ep| ep.body.is_some() || ep.response.is_some());
    let has_api_types =
        !schema.requests.is_empty() || !schema.responses.is_empty() || !schema.errors.is_empty();
    let has_auth = schema.endpoints.iter().any(|ep| ep.auth != AuthMode::None);

    out.push_str("use axum::extract::State;\n");
    if has_path_params {
        out.push_str("use axum::extract::Path;\n");
    }
    if has_json {
        out.push_str("use axum::Json;\n");
    }
    if has_auth {
        out.push_str("use ag_core::core::Claims;\n");
    }
    out.push_str("use super::AppState;\n");
    if has_api_types {
        out.push_str("use super::types::*;\n");
    }
    out.push('\n');
    for ep in &schema.endpoints {
        out.push_str(&generate_handler_stub(ep));
        out.push('\n');
    }
    out
}

fn generate_handler_stub(ep: &EndpointDef) -> String {
    let fn_name = to_snake_case(&ep.name.value);
    let method_str = ep.method.value.as_str();
    let path_str = &ep.path.value;
    let path_params = extract_path_params(path_str);

    let mut params = vec!["State(state): State<AppState>".to_owned()];
    for param in &path_params {
        params.push(format!("Path({param}): Path<String>"));
    }
    // v0.5: Claims extractor when the endpoint requires authentication.
    if ep.auth != AuthMode::None {
        params.push("Claims(claims): Claims<serde_json::Value>".to_owned());
    }
    if let Some(body) = &ep.body {
        params.push(format!("Json(body): Json<{}>", body.value));
    }

    let return_ty = if let Some(resp) = &ep.response {
        format!("Result<Json<{}>, axum::http::StatusCode>", resp.value)
    } else {
        "axum::http::StatusCode".to_owned()
    };

    let mut out = String::new();
    out.push_str(&format!(
        "/// {method_str} {path_str} - {}\n",
        ep.name.value
    ));
    out.push_str(&format!(
        "pub async fn {fn_name}(\n    {}\n) -> {return_ty} {{\n",
        params.join(",\n    ")
    ));
    // v0.6: event stubs declared by the endpoint.
    for event in &ep.emits {
        out.push_str(&format!(
            "    // TODO: state.events.emit(\"{}\", &payload).await?;\n",
            event.value
        ));
    }
    out.push_str("    todo!()\n}\n");
    out
}

/// Generates `src/router.rs`: Axum route registration.
pub fn generate_router(schema: &Schema) -> String {
    if schema.endpoints.is_empty() {
        return String::new();
    }
    use crate::ast::dsl_path_to_axum;

    let mut out = String::new();
    out.push_str("//! Router generated by Anti-Gravital ag-dsl v0.2.\n\n");
    out.push_str("use axum::routing;\n");
    out.push_str("use super::{handlers, AppState};\n\n");
    out.push_str("/// Creates the Axum router with all routes defined in the schema.\n");
    out.push_str("pub fn api_router() -> axum::Router<AppState> {\n");
    out.push_str("    axum::Router::new()\n");

    for ep in &schema.endpoints {
        let fn_name = to_snake_case(&ep.name.value);
        let axum_path = dsl_path_to_axum(&ep.path.value);
        let axum_method = match ep.method.value {
            HttpMethod::Get => "get",
            HttpMethod::Post => "post",
            HttpMethod::Put => "put",
            HttpMethod::Patch => "patch",
            HttpMethod::Delete => "delete",
        };
        out.push_str(&format!(
            "        .route(\"{axum_path}\", routing::{axum_method}(handlers::{fn_name}))\n"
        ));
    }
    out.push_str("}\n");
    out
}

// ---- DSL v0.3 validation: validate() method -------------------------

/// Generates an `impl StructName { pub fn validate(...) }` block with
/// every check derived from validation annotations.
/// Returns an empty string when fields have no validation annotations.
fn generate_validate_impl(struct_name: &str, fields: &[FieldDef]) -> String {
    let mut checks = Vec::new();

    for field in fields {
        let fname = &field.name.value;
        let string_value = if field.optional {
            "value".to_owned()
        } else {
            format!("self.{fname}")
        };
        let scalar_value = if field.optional {
            "*value".to_owned()
        } else {
            format!("self.{fname}")
        };

        let mut regex_count = 0;
        for ann in &field.annotations {
            let check = match (&ann.value, &field.ty.value) {
                (Annotation::Min(n), FieldType::String) => Some(validation_block(
                    field,
                    format!("{string_value}.len() < {n}"),
                    format!(
                        "errors.push(format!(\"{fname}: minimum length is {n}, found {{}} characters\", {string_value}.len()));"
                    ),
                )),
                (Annotation::Max(n), FieldType::String) => Some(validation_block(
                    field,
                    format!("{string_value}.len() > {n}"),
                    format!(
                        "errors.push(format!(\"{fname}: maximum length is {n}, found {{}} characters\", {string_value}.len()));"
                    ),
                )),
                (Annotation::Min(n), FieldType::Int) => Some(validation_block(
                    field,
                    format!("{scalar_value} < {n}"),
                    format!("errors.push(\"{fname}: minimum value is {n}\".to_owned());"),
                )),
                (Annotation::Max(n), FieldType::Int) => Some(validation_block(
                    field,
                    format!("{scalar_value} > {n}"),
                    format!("errors.push(\"{fname}: maximum value is {n}\".to_owned());"),
                )),
                (Annotation::Min(n), FieldType::Float) => Some(validation_block(
                    field,
                    format!("{scalar_value} < {n}f64"),
                    format!("errors.push(\"{fname}: minimum value is {n}\".to_owned());"),
                )),
                (Annotation::Max(n), FieldType::Float) => Some(validation_block(
                    field,
                    format!("{scalar_value} > {n}f64"),
                    format!("errors.push(\"{fname}: maximum value is {n}\".to_owned());"),
                )),
                (Annotation::Min(n), FieldType::Decimal) => {
                    let condition = if field.optional {
                        format!(
                            "value < &rust_decimal::Decimal::from({n})"
                        )
                    } else {
                        format!(
                            "self.{fname} < rust_decimal::Decimal::from({n})"
                        )
                    };
                    Some(validation_block(
                        field,
                        condition,
                        format!("errors.push(\"{fname}: minimum value is {n}\".to_owned());"),
                    ))
                }
                (Annotation::Max(n), FieldType::Decimal) => {
                    let condition = if field.optional {
                        format!(
                            "value > &rust_decimal::Decimal::from({n})"
                        )
                    } else {
                        format!(
                            "self.{fname} > rust_decimal::Decimal::from({n})"
                        )
                    };
                    Some(validation_block(
                        field,
                        condition,
                        format!("errors.push(\"{fname}: maximum value is {n}\".to_owned());"),
                    ))
                }
                (Annotation::Email, FieldType::String) => {
                    let condition = format!(
                        "!({string_value}.contains('@') && {string_value}.rfind('@')\n\
                         .map(|i| {string_value}[i + 1..].contains('.'))\n\
                         .unwrap_or(false))"
                    );
                    Some(validation_block(
                        field,
                        condition,
                        format!("errors.push(\"{fname}: invalid email format\".to_owned());"),
                    ))
                }
                (Annotation::Length(n), FieldType::String) => Some(validation_block(
                    field,
                    format!("{string_value}.len() != {n}"),
                    format!(
                        "errors.push(format!(\"{fname}: exact length required is {n}, found {{}} characters\", {string_value}.len()));"
                    ),
                )),
                (Annotation::Regex(pattern), FieldType::String) => {
                    let target = if field.optional {
                        "value.as_str()".to_owned()
                    } else {
                        format!("self.{fname}.as_str()")
                    };
                    regex_count += 1;
                    let suffix = if regex_count == 1 {
                        String::new()
                    } else {
                        format!("_{regex_count}")
                    };
                    let static_name = format!(
                        "{}_{}_REGEX{suffix}",
                        to_snake_case(struct_name).to_ascii_uppercase(),
                        fname.to_ascii_uppercase()
                    );
                    let condition = format!(
                        "!{static_name}.get_or_init(|| regex::Regex::new({pattern:?})\n\
                         .expect(\"the DSL compiler validated this @regex pattern\"))\n\
                         .is_match({target})"
                    );
                    Some(format!(
                        "    static {static_name}: std::sync::OnceLock<regex::Regex> = std::sync::OnceLock::new();\n{}",
                        validation_block(
                            field,
                            condition,
                            format!("errors.push(\"{fname}: value does not match required pattern\".to_owned());"),
                        )
                    ))
                }
                _ => None,
            };
            if let Some(check) = check {
                checks.push(check);
            }
        }
    }

    if checks.is_empty() {
        return String::new();
    }

    let mut out = String::new();
    out.push_str(&format!(
        "\nimpl {struct_name} {{\n\
         /// Validates every constraint declared in the DSL schema.\n\
         /// Returns all validation errors; an empty list means the value is valid.\n\
         pub fn validate(&self) -> Vec<String> {{\n\
             let mut errors: Vec<String> = Vec::new();\n"
    ));
    for check in checks {
        out.push_str(&check);
        out.push('\n');
    }
    out.push_str("    errors\n}\n}\n");
    out
}

fn validation_block(field: &FieldDef, condition: String, error: String) -> String {
    let fname = &field.name.value;
    if field.optional {
        format!(
            "    if let Some(value) = &self.{fname} {{\n\
             \x20       if {condition} {{\n\
             \x20           {error}\n\
             \x20       }}\n\
             \x20   }}"
        )
    } else {
        format!(
            "    if {condition} {{\n\
             \x20       {error}\n\
             \x20   }}"
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::tokenize;
    use crate::parser::parse_tokens;

    fn schema_from(src: &str) -> Schema {
        let (tokens, _) = tokenize(src);
        let (ast, _) = parse_tokens(tokens, src.len());
        ast.expect("valid schema")
    }

    #[test]
    fn rust_gen_includes_claims_when_auth_required() {
        let src = r#"
endpoint GetProfile {
    method GET
    path /profile
    auth required
    response UserResponse
}
response UserResponse { id UUID }
"#;
        let schema = crate::compile(src).unwrap();
        let files = crate::generate(&schema);
        let handlers = files
            .files
            .iter()
            .find(|(p, _)| p.to_str().unwrap_or("").contains("handlers"))
            .map(|(_, c)| c.clone())
            .unwrap_or_default();
        assert!(
            handlers.contains("Claims"),
            "must include Claims when auth is required, got:\n{}",
            handlers
        );
    }

    #[test]
    fn rust_gen_includes_event_stub_in_handler() {
        let src = r#"
event user.created { payload UserResponse }
endpoint CreateUser {
    method POST
    path /users
    auth required
    events [user.created]
}
response UserResponse { id UUID }
"#;
        let schema = crate::compile(src).unwrap();
        let files = crate::generate(&schema);
        let handlers = files
            .files
            .iter()
            .find(|(p, _)| p.to_str().unwrap_or("").contains("handlers"))
            .map(|(_, c)| c.clone())
            .unwrap_or_default();
        assert!(
            handlers.contains("user.created"),
            "must include an event stub, got:\n{}",
            handlers
        );
    }

    #[test]
    fn generates_valid_struct() {
        let schema = schema_from(
            r#"
model User {
    id    UUID   @primary @auto
    email String @unique
    name  String
}
"#,
        );
        let out = generate_models(&schema);
        assert!(out.contains("pub struct User {"));
        assert!(out.contains("pub struct CreateUserRequest {"));
        assert!(out.contains("pub struct UpdateUserRequest {"));
        // The id field (@auto) must not appear in CreateRequest
        assert!(!out.contains("pub struct CreateUserRequest {\n    pub id:"));
    }

    #[test]
    fn optional_field_in_update_request() {
        let schema = schema_from(
            r#"
model Post {
    id      UUID   @primary @auto
    title   String
    content String?
}
"#,
        );
        let out = generate_models(&schema);
        assert!(out.contains("pub title: Option<String>,"));
        assert!(out.contains("pub content: Option<String>,"));
    }

    #[test]
    fn uuid_import_included() {
        let schema = schema_from(
            r#"
model Item {
    id UUID @primary @auto
    v  Int
}
"#,
        );
        let out = generate_models(&schema);
        assert!(out.contains("use uuid::Uuid;"));
    }

    // ---- Tests DSL v0.4 ----

    #[test]
    fn v04_model_ref_generates_option() {
        let schema = schema_from(
            r#"
model User {
    id    UUID @primary @auto
    email String
}
model Post {
    id        UUID @primary @auto
    title     String
    author_id UUID @references(User.id)
    author    User @relation(author_id)
}
"#,
        );
        let out = generate_models(&schema);
        assert!(
            out.contains("pub author: Option<User>"),
            "N:1 virtual field should be Option<User>. Output:\n{out}"
        );
        assert!(
            out.contains("pub author_id:"),
            "FK field must be in struct. Output:\n{out}"
        );
    }

    #[test]
    fn v04_model_ref_list_generates_vec() {
        let schema = schema_from(
            r#"
model User {
    id    UUID   @primary @auto
    posts Post[] @relation(post.author_id)
}
model Post {
    id        UUID @primary @auto
    author_id UUID @references(User.id)
}
"#,
        );
        let out = generate_models(&schema);
        assert!(
            out.contains("pub posts: Vec<Post>"),
            "1:N virtual field should be Vec<Post>. Output:\n{out}"
        );
    }

    #[test]
    fn v04_virtual_field_excluded_from_create_request() {
        let schema = schema_from(
            r#"
model Post {
    id        UUID @primary @auto
    title     String
    author_id UUID @references(User.id)
    author    User @relation(author_id)
}
model User {
    id UUID @primary @auto
}
"#,
        );
        let out = generate_models(&schema);
        let create_start = out.find("pub struct CreatePostRequest").unwrap_or(0);
        let create_end = out[create_start..]
            .find('}')
            .unwrap_or(out.len() - create_start)
            + create_start;
        let create_body = &out[create_start..create_end];
        assert!(
            !create_body.contains("author:"),
            "virtual field should not appear in CreateRequest. Body:\n{create_body}"
        );
    }

    #[test]
    fn generated_module_owns_shared_state_and_submodules() {
        let schema = schema_from(
            r#"
request UpdateUser { email String }
response UserResponse { id UUID }
endpoint UpdateUser {
    method PATCH
    path /users/{id}
    auth required
    body UpdateUser
    response UserResponse
}
"#,
        );

        let module = generate_module(&schema);
        assert!(module.contains("pub mod handlers;"));
        assert!(module.contains("pub mod router;"));
        assert!(module.contains("pub type AppState = ag_core::core::AppState;"));

        let handlers = generate_handlers(&schema);
        assert!(handlers.contains("use ag_core::core::Claims;"));
        assert!(handlers.contains("use super::AppState;"));
        assert!(handlers.contains("use super::types::*;"));
        assert!(handlers.contains("use axum::extract::Path;"));

        let router = generate_router(&schema);
        assert!(router.contains("use super::{handlers, AppState};"));
        assert!(!router.contains("pub type AppState"));
    }

    #[test]
    fn optional_and_decimal_validations_emit_type_correct_checks() {
        let schema = schema_from(
            r#"
request Metrics {
    attempts Int? @min(1)
    ratio Float? @max(10)
    amount Decimal? @min(0)
    email String? @email
}
"#,
        );

        let out = generate_types(&schema);
        assert!(out.contains("if let Some(value) = &self.attempts"));
        assert!(out.contains("*value < 1"));
        assert!(out.contains("*value > 10f64"));
        assert!(out.contains("value < &rust_decimal::Decimal::from(0)"));
        assert!(out.contains("if let Some(value) = &self.email"));
        assert!(!out.contains("as i64"));
    }

    #[test]
    fn regex_validation_is_executable_and_cached() {
        let schema = schema_from(
            r#"
request UpdateUser {
    username String @regex("^[a-z][a-z0-9_]{2,15}$") @regex("^[a-z]")
}
"#,
        );
        let out = generate_types(&schema);
        assert!(
            out.contains("static UPDATE_USER_USERNAME_REGEX: std::sync::OnceLock<regex::Regex>")
        );
        assert!(out.contains("regex::Regex::new(\"^[a-z][a-z0-9_]{2,15}$\")"));
        assert!(
            out.contains("static UPDATE_USER_USERNAME_REGEX_2: std::sync::OnceLock<regex::Regex>")
        );
        assert_eq!(out.matches(".is_match(self.username.as_str())").count(), 2);
        assert!(!out.contains("TODO(#70)"));
    }

    #[test]
    fn no_uuid_import_when_not_needed() {
        let schema = schema_from(
            r#"
model Counter {
    id    Int    @primary @auto
    value Int
}
"#,
        );
        let out = generate_models(&schema);
        assert!(!out.contains("use uuid::Uuid;"));
    }
}
